### ISSUE TITLE
Can you please enable discussions?

### ISSUE THREAD

**Issue by daninus14** [fukamachi/mito#146]
I think it will help for people to ask questions that are not necessarily issues with the code...

**Comment by fukamachi** [comment]
Okay.

**Comment by fukamachi** [comment]
It seems it's already available.
Can you make a new Q&A discussion from [here](https://github.com/fukamachi/mito/discussions/new?category=q-a)?

**Comment by daninus14** [comment]
Great! Thanks for enabling them!
