### ISSUE TITLE
:col-type "decimal(10,2)" does not work in CCL but ok in SBCL

### ISSUE THREAD

**Issue by kongotania** [fukamachi/mito#165]
The following  class definition 

```
(mito:deftable prueba ()
  ((col1 :col-type :text :initarg :col1)
   (col2 :col-type "decimal(10,2)" :initarg :col2)))
```

compiles OK in sbcl , but when executed in CCL raises the following error:

The value "decimal(10,2)", derived from the initarg :COL-TYPE, can not be used to set the value of the slot MITO.CLASS.COLUMN::COL-TYPE in #<DAO-TABLE-COLUMN-CLASS for instance slot COL2 #x3020035AC46D>, because it is not of type (OR CONS SYMBOL).

Looking for TABLE-COLUMN-CLASS the slot COL-TYPE has the following type specification 
```
(col-type :type (or symbol cons null)
             :initarg :col-type
             :accessor %table-column-type)
```

And so the error that raises is ok because it does not allows strings.  But the documentation  in section :col-type Definitions with Qualifiers allows for string specifications. 

For why IT gives an error in CCL but no in SBCL is probably that they handle type assertions in DEFCLASS in a different way. 

Probably adding String to the type spec will fix the issue.

**Comment by fukamachi** [comment]
It is intended even though SBCL skips the type checking. Use `(:decimal 10 2)` instead.

**Comment by kongotania** [comment]
Worked ok. I was confused by documentation.
