### ISSUE TITLE
migrate-table fails on datetime fields with postgres

### ISSUE THREAD

**Issue by slyrus** [fukamachi/mito#18]
I'm a bit confused as to how this ever worked (or if I just overlooked the fact that it didn't), but migrate-table calls fail for dao-table-class in postgres instances because of the created-at and updated-at fields. These are defined as being of col-type (or :datetime :null) and the code in table-column-info-for-create-table was converting the column type from :datetime to :time. It seems to me that this should be done in table-column-info instead of table-column-info-for-create-table. See soon-to-be-pending pull request.

**Comment by fukamachi** [comment]
Fixed at #21.
`TIME` was wrong for the replacement of `DATETIME`, so the column type has been changed to `TIMESTAMP`.
Thank you for reporting and sending a PR.
