### ISSUE TITLE
Does not load (LispWorks 6.0.1 on Windows)

### ISSUE THREAD

**Issue by franksmuc** [fukamachi/mito#24]
To load "mito":
  Load 1 ASDF system:
    mito
; Loading "mito"
..................................................
........

[package mito.dao.mixin].

**++++ Error in (DEFCLASS MITO.DAO.MIXIN:AUTO-PK-MIXIN): 
  #<STANDARD-GENERIC-FUNCTION CLOS:DIRECT-SLOT-DEFINITION-CLASS 20A63A02> is called with keyword :NAME among the arguments (#<DAO-TABLE-MIXIN AUTO-PK-MIXIN 230498FB> :NAME ID :READERS (OBJECT-ID) :INITARGS (:ID) :PRIMARY-KEY T :COL-TYPE :BIGSERIAL) when no keywords are allowed.

**++++ Error in (DEFCLASS MITO.DAO.MIXIN:RECORD-TIMESTAMPS-MIXIN): 
  #<STANDARD-GENERIC-FUNCTION CLOS:DIRECT-SLOT-DEFINITION-CLASS 20A63A02> is called with keyword :NAME among the arguments (#<DAO-TABLE-MIXIN RECORD-TIMESTAMPS-MIXIN 200BBCDB> :NAME CREATED-AT :READERS (OBJECT-CREATED-AT) :WRITERS ((SETF OBJECT-CREATED-AT)) :INITARGS (:CREATED-AT) :COL-TYPE (OR :DATETIME :NULL)) when no keywords are allowed.
; *** 2 errors detected, no fasl file produced.

(:MITO)

**Comment by fukamachi** [comment]
LispWorks isn't supported as I never use it. Pull request is welcomed.

**Comment by franksmuc** [comment]
This is solved now. Thank you for making mito
