### ISSUE TITLE
Self referencing col-type 

### ISSUE THREAD

**Issue by knobo** [fukamachi/mito#26]
Any posibility to make something like this work?
``` cl
(defclass category ()
  ((parent :col-type category
	   :initarg :parent
	   :accessor parent))
  (:metaclass mito:dao-table-class))
```

**Comment by Mr-Dispatch** [comment]
Fugly work-around is to deftable the same table twice (first time with no fields).

It didn't even occur to me this is not supported, and as I built-up my prototype I just loaded a new definition with self-reference over the previous one, and it worked ... ... ... until I restarted the REPL and tried to load the project from scratch.
