### ISSUE TITLE
Unbound variable: DBD.SQLITE3::PREPARED

### ISSUE THREAD

**Issue by vrx** [fukamachi/mito#44]
hi and thanks for this very nice work !

with sqlite3
making a new table, migrating, creating dao, issues the same error

**Unbound variable: DBD.SQLITE3::PREPARED**

unless using previous version of cl-dbi/src/dbd/sqlite3.lisp
https://github.com/fukamachi/cl-dbi/commit/9691a6a5f8e798c383e289880c17222520db121d#diff-db0af84ec3972649eec69d0ce34e150e

**Comment by atgreen** [comment]
I get this error on travis-ci, where they have these versions...

libsqlite3-0/trusty-updates,trusty-security,now 3.8.2-1ubuntu2.1 amd64 [installed]
libsqlite3-dev/trusty-updates,trusty-security,now 3.8.2-1ubuntu2.1 amd64 [installed]

However, I don't get this on my Fedora box, where I have this:

$ rpm -qa sqlite\*
sqlite-3.26.0-1.fc29.x86_64
sqlite-libs-3.26.0-1.fc29.x86_64
sqlite-libs-3.26.0-1.fc29.i686

Any ideas?

**Comment by vrx** [comment]
on ubuntu 17.10, changing sqlite3 version does not change anything.
sqlite3 version 3.19.3-3 gives me this error
sqlite3 version 3.26.0  gives me this error too

**Comment by fukamachi** [comment]
Fixed in https://github.com/fukamachi/cl-dbi/commit/fcb4d2e3d0139fc8b6b9184ad9194d689058e949.
