### ISSUE TITLE
Relationship queries fail when (setf *print-case* :downcase)

### ISSUE THREAD

**Issue by Ambrevar** [fukamachi/mito#45]
If `*print-case*` is not `:UPCASE`, it seems that Mito fails to retrieve relationship fields via accessors.  Example:

``` lisp
(setf *print-case* :downcase)

(deftable user ()
  ((name :col-type (:varchar 512)))))

(deftable tweet ()
  ((status :col-type (:varchar 512))))
  ((user  :col-type user)))
  

(let* ((user (create-dao 'user :name "foo"))
       (tweet (create-dao 'tweet :status "bar" :user user)))
  (user tweet))
```

The last expression returns `nil`, while it should return some `#<USER {...}>` object.

**Comment by vindarel** [comment]
reproduced here. (Thanks for the report!!)

**Comment by vindarel** [comment]
related: https://github.com/fukamachi/quri/pull/24/

**Comment by vindarel** [comment]
tested better by putting my changes in local-projects: it works for me©.
