### ISSUE TITLE
Logger Error on ECL. (There exists no package with name NIL)

### ISSUE THREAD

**Issue by iarebatman** [fukamachi/mito#90]
Error Condition

![image](https://user-images.githubusercontent.com/1566535/119850003-bf7d4680-bed2-11eb-8f4e-dfac6453fdf9.png)

It looks like it's trying to use something called `COMMON-LISP:PACKAGE`, which is NIL for me on ECL..

Backtrace:

![image](https://user-images.githubusercontent.com/1566535/119848830-c061a880-bed1-11eb-8881-21cc4e810502.png)

I believe the problem might be happening on line 44  here, but I'm not sure.. I'm not very fluent in CL yet..

![image](https://user-images.githubusercontent.com/1566535/119849203-0e76ac00-bed2-11eb-97c8-e750b9d4a165.png)

**Comment by iarebatman** [comment]
Just to follow up, I added a `#-ecl` to the beginning of line 44 and that allowed mito to start behaving correctly.  I kind of feel like that's a hack because I don't quite understand the intent behind this code at the moment, but I'm hoping that helps someone more knowledgeable provide a more accurate fix..  I honestly expected logging to not work at all once I did that, but my sql traces are actually working now, so I'm not sure that anything is broken..  Let me know if I can provide any additional data to help.

**Comment by fukamachi** [comment]
Sorry for the delay.
Thank you for your perfect report! The stack trace is very helpful.
It seems `call` can be a not-interned symbol and `(symbol-package call)` returns `nil` for it.
I'm going to fix it tonight.

**Comment by iarebatman** [comment]
No need to apologize, you don’t owe me anything. I appreciate the proper fix though, thank you! :-)
